; PlatformIO Project Configuration File
; ESP32-C3 Super Mini — Light Painting Tool

[env:esp32-c3-supermini]
platform = espressif32
board = lolin_c3_mini
framework = arduino
monitor_speed = 115200
board_build.flash_mode = qio
upload_protocol = esptool
board_upload.before_reset = usb_reset
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    fastled/FastLED @ ^3.9.0
    esphome/ESPAsyncWebServer-esphome @ ^3.3.0
    bblanchon/ArduinoJson @ ^7.0.0
